/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews
 */
public class TelaAlterarLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAlterarLivro
     */
    public TelaAlterarLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jButtonVer = new javax.swing.JButton();
        jLabelEditora = new javax.swing.JLabel();
        jTextFieldEditora = new javax.swing.JTextField();
        jButtonAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TelaFundo = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jLabelAutor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAutor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAutor.setText("Autor");
        jPanel1.add(jLabelAutor);
        jLabelAutor.setBounds(40, 10, 50, 17);
        jPanel1.add(jTextFieldAutor);
        jTextFieldAutor.setBounds(40, 30, 430, 30);

        jButtonVer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonVer.setText("Listar");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVer);
        jButtonVer.setBounds(40, 70, 90, 30);

        jLabelEditora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEditora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditora.setText("Editora");
        jPanel1.add(jLabelEditora);
        jLabelEditora.setBounds(40, 110, 50, 30);
        jPanel1.add(jTextFieldEditora);
        jTextFieldEditora.setBounds(100, 110, 250, 30);

        jButtonAtualizar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAtualizar);
        jButtonAtualizar.setBounds(380, 110, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Edição", "Editora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 170, 530, 220);

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4.png"))); // NOI18N
        jPanel1.add(TelaFundo);
        TelaFundo.setBounds(0, 0, 530, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 545, 414);
    }// </editor-fold>//GEN-END:initComponents

    Biblioteca biblioteca = Biblioteca.getInstancia();
    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
        int aux = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object romData[] = new Object[5];
        
        model.setNumRows(0);
        if(jTextFieldAutor.getText().length() > 0){
            for(int i=0; i <biblioteca.getLivros().size(); i++ ){
                if(biblioteca.livros.get(i).getAutor().equalsIgnoreCase(jTextFieldAutor.getText())){
                    romData[0] = biblioteca.livros.get(i).getTitulo();
                    romData[1] = biblioteca.livros.get(i).getAutor();
                    romData[2] = biblioteca.livros.get(i).getEdicao();
                    romData[3] = biblioteca.livros.get(i).getEditora();
                    romData[4] =biblioteca.livros.get(i).getAnoLancamento();
                    model.addRow(romData); 
                    aux++;
                }
            }
            if(aux==0){
                mensagemWarning("NEM UM LIVRO CADASTRADO COM ESTE AUTOR!");
            }
        }else{
            for(int i=0; i <biblioteca.getLivros().size(); i++ ){
                romData[0] = biblioteca.livros.get(i).getTitulo();
                romData[1] = biblioteca.livros.get(i).getAutor();
                romData[2] = biblioteca.livros.get(i).getEdicao();
                romData[3] = biblioteca.livros.get(i).getEditora();
                romData[4] =biblioteca.livros.get(i).getAnoLancamento();
                model.addRow(romData);              
            }
        }   
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        Object romData[] = new Object[5];
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int posicao = jTable1.getSelectedRow();
        biblioteca.livros.get(posicao).setEditora(jTextFieldEditora.getText());
        
        System.out.println(jTable1.getSelectedRow());
        
        model.setNumRows(0);
        romData[0] = biblioteca.livros.get(posicao).getTitulo();
        romData[1] = biblioteca.livros.get(posicao).getAutor();
        romData[2] = biblioteca.livros.get(posicao).getEdicao();
        romData[3] = biblioteca.livros.get(posicao).getEditora();
        romData[4] =biblioteca.livros.get(posicao).getAnoLancamento();
        model.addRow(romData);   
        mensagemSucesso("LIVRO ALTERADO!!!");
        
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

     public void mensagemWarning(String mensagem){
         JOptionPane.showMessageDialog(null, mensagem, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
    }
     
     public void mensagemSucesso(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem, "SUCCESS", JOptionPane.PLAIN_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditora;
    // End of variables declaration//GEN-END:variables
}
