/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import ParteGrafica.*;

/**
 *
 * @author Mathews
 */
public class TelaInicialCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialCliente
     */
    public TelaInicialCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoTela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuLivro = new javax.swing.JMenu();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemAlterarDados = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        FundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N
        getContentPane().add(FundoTela);
        FundoTela.setBounds(0, 0, 710, 530);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/page.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");
        jMenuArquivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/door_out.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuItemFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/cross.png"))); // NOI18N
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemFechar);

        jMenuBar1.add(jMenuArquivo);

        jMenuLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/book.png"))); // NOI18N
        jMenuLivro.setText("Livros");
        jMenuLivro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/book_open.png"))); // NOI18N
        jMenuItemListar.setText("Realizar Emprestimo");
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuLivro.add(jMenuItemListar);

        jMenuBar1.add(jMenuLivro);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/user.png"))); // NOI18N
        jMenuCliente.setText("Usuário");
        jMenuCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenuItemAlterarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/user_edit.png"))); // NOI18N
        jMenuItemAlterarDados.setText("Alterar Dados");
        jMenuCliente.add(jMenuItemAlterarDados);

        jMenuBar1.add(jMenuCliente);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PacoteDeIcones/information.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(713, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoTela;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAlterarDados;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuLivro;
    private javax.swing.JMenu jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
