/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

/**
 *
 * @author Mathews
 */
public class TelaExcluirCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaExcluirCliente
     */
    public TelaExcluirCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelRG = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jButtonVer = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TelaFundo = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        jPanel1.add(jLabelNome);
        jLabelNome.setBounds(20, 20, 50, 30);
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(70, 20, 260, 30);

        jLabelRG.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRG.setText("RG");
        jPanel1.add(jLabelRG);
        jLabelRG.setBounds(350, 30, 21, 17);
        jPanel1.add(jTextFieldRG);
        jTextFieldRG.setBounds(380, 20, 130, 30);

        jButtonVer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonVer.setText("Ver");
        jPanel1.add(jButtonVer);
        jButtonVer.setBounds(70, 60, 80, 30);

        jButtonExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(430, 60, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "RG", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 130, 530, 260);

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4.png"))); // NOI18N
        jPanel1.add(TelaFundo);
        TelaFundo.setBounds(0, 0, 530, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 545, 414);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables
}
