/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mathews
 */
public class TelaFormularioCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente2
     */
    public TelaFormularioCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDadosPessoais = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabelContato = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabelCelular = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabelDia = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxAno = new javax.swing.JComboBox<>();
        jLabelAno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelDadosPessoais.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDadosPessoais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDadosPessoais.setText("Dados Pessoais");
        getContentPane().add(jLabelDadosPessoais);
        jLabelDadosPessoais.setBounds(10, 10, 120, 17);

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(40, 30, 40, 17);
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(40, 60, 320, 30);

        jLabelDataNasc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNasc.setText("Data Nasc");
        getContentPane().add(jLabelDataNasc);
        jLabelDataNasc.setBounds(40, 90, 80, 17);

        jLabelSexo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(380, 40, 40, 17);

        jComboBoxSexo.setEditable(true);
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", " " }));
        getContentPane().add(jComboBoxSexo);
        jComboBoxSexo.setBounds(380, 60, 110, 30);

        jLabelContato.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelContato.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContato.setText("Contato");
        getContentPane().add(jLabelContato);
        jLabelContato.setBounds(10, 180, 60, 17);

        jLabelTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(30, 210, 70, 17);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldTelefone);
        jFormattedTextFieldTelefone.setBounds(30, 230, 320, 30);

        jLabelCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCelular.setText("Celular");
        getContentPane().add(jLabelCelular);
        jLabelCelular.setBounds(30, 270, 60, 10);

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCelular);
        jFormattedTextFieldCelular.setBounds(30, 290, 320, 30);

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(30, 330, 40, 17);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(30, 350, 320, 30);

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(380, 390, 80, 30);

        jComboBoxDia.setEditable(true);
        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDia);
        jComboBoxDia.setBounds(70, 120, 60, 30);

        jLabelDia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDia.setText("Dia");
        getContentPane().add(jLabelDia);
        jLabelDia.setBounds(40, 120, 24, 30);

        jComboBoxMes.setEditable(true);
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBoxMes);
        jComboBoxMes.setBounds(190, 120, 70, 30);

        jLabelMes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMes.setText("Mês");
        getContentPane().add(jLabelMes);
        jLabelMes.setBounds(150, 120, 34, 30);

        jComboBoxAno.setEditable(true);
        jComboBoxAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jComboBoxAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAno);
        jComboBoxAno.setBounds(320, 120, 80, 30);

        jLabelAno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAno.setText("Ano");
        getContentPane().add(jLabelAno);
        jLabelAno.setBounds(280, 117, 31, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 440);

        setSize(new java.awt.Dimension(536, 470));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    Biblioteca biblioteca = Biblioteca.getInstancia();
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        String nome;
        String email;
        String telefone;
        String celular;
        String sexo;
        int dia, mes, ano;
        
        try{
            nome = getTextFieldData(jTextFieldNome);
            sexo = getComboBoxData(jComboBoxSexo);
            email = getTextFieldData(jTextFieldEmail);
            telefone = getTextFieldData(jFormattedTextFieldTelefone);
            celular = getTextFieldData(jFormattedTextFieldCelular);
            dia = Integer.parseInt(getComboBoxData(jComboBoxDia));
            mes = Integer.parseInt(getComboBoxData(jComboBoxMes));
            ano = Integer.parseInt(getComboBoxData(jComboBoxAno));
            
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).nome = nome;
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).sexo = sexo;
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).setEmail(email);
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).telefoneFixo = telefone;
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).telefoneCelular = celular;
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).dataNasc.setDia(dia);
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).dataNasc.setMes(mes);
            biblioteca.clientes.get(biblioteca.clientes.size() - 1).dataNasc.setAno(ano);
            
            mensagemSucesso("CADASTRO REALIZADO COM SUCESSO!!!");
            dispose();
            
        } catch (FaltamDadosException ex) {
           // Logger.getLogger(TelaFormularioCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
           ex.View();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnoActionPerformed
 
    }//GEN-LAST:event_jComboBoxAnoActionPerformed

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiaActionPerformed
    
     public String getTextFieldData(JTextField jtext) throws FaltamDadosException {
		String s = jtext.getText();
		if (s.equals(""))
			throw new FaltamDadosException("Preencha todos os campos!");
		return s;
    }
     
     public String getComboBoxData(JComboBox jbox) throws FaltamDadosException {
		if (jbox.getSelectedIndex() == -1)
			throw new FaltamDadosException("Por Favor Preecha a Sua Data de Nascimento");
		String s = jbox.getItemAt(jbox.getSelectedIndex()).toString();
		return s;
    }
     
     public void mensagemSucesso(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem, "SUCCESS", JOptionPane.PLAIN_MESSAGE);
    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFormularioCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxAno;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelContato;
    private javax.swing.JLabel jLabelDadosPessoais;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
