/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mathews
 */
public class TelaExcluirLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaExcluirLivro
     */
    public TelaExcluirLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        FundoTela = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Titulo");
        jPanel1.add(jLabelTitulo);
        jLabelTitulo.setBounds(40, 20, 50, 30);
        jPanel1.add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(90, 20, 410, 30);

        jButtonExcluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir);
        jButtonExcluir.setBounds(250, 60, 90, 30);

        jButtonVer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonVer.setText("Listar");
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVer);
        jButtonVer.setBounds(90, 60, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "ID", "Autor", "Edição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 120, 530, 270);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 60, 90, 30);

        FundoTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3.jpg"))); // NOI18N
        jPanel1.add(FundoTela);
        FundoTela.setBounds(0, 0, 530, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 545, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int posicao = jTable1.getSelectedRow();
        biblioteca.livros.remove(posicao);
        ((DefaultTableModel) jTable1.getModel()).removeRow(jTable1.getSelectedRow());
    }//GEN-LAST:event_jButtonExcluirActionPerformed
    
    Biblioteca biblioteca = Biblioteca.getInstancia();
    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        // TODO add your handling code here:
        int aux = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object romData[] = new Object[5];
        
        model.setNumRows(0);
        if(jTextFieldTitulo.getText().length() > 0){
            for(int i=0; i <biblioteca.getLivros().size(); i++ ){
                if(biblioteca.livros.get(i).getTitulo().equalsIgnoreCase(jTextFieldTitulo.getText())){
                    romData[0] = biblioteca.livros.get(i).getTitulo();
                    romData[1] = biblioteca.livros.get(i).getAutor();
                    romData[2] = biblioteca.livros.get(i).getEdicao();
                    romData[3] = biblioteca.livros.get(i).getEditora();
                    romData[4] = biblioteca.livros.get(i).getAnoLancamento();
                    model.addRow(romData); 
                    aux++;
                }
            }
            if(aux==0){
                mensagemWarning("LIVRO NÃO CADASTRADO!!!");
            }
        }else{
            for(int i=0; i <biblioteca.getLivros().size(); i++ ){
                romData[0] = biblioteca.livros.get(i).getTitulo();
                romData[1] = biblioteca.livros.get(i).getAutor();
                romData[2] = biblioteca.livros.get(i).getEdicao();
                romData[3] = biblioteca.livros.get(i).getEditora();
                romData[4] =biblioteca.livros.get(i).getAnoLancamento();
                model.addRow(romData);              
            }
        }   
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
     public void mensagemWarning(String mensagem){
         JOptionPane.showMessageDialog(null, mensagem, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoTela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
