/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParteGrafica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mathews
 */
public class TelaCadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelConfirmarSenha = new javax.swing.JLabel();
        jPasswordFieldConfirmarSenha = new javax.swing.JPasswordField();
        jButtonSalvar = new javax.swing.JButton();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        TelaFundo = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuário");
        jPanel1.add(jLabelUsuario);
        jLabelUsuario.setBounds(150, 90, 60, 17);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(150, 110, 260, 30);

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        jPanel1.add(jLabelSenha);
        jLabelSenha.setBounds(150, 150, 44, 17);
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(150, 170, 260, 30);

        jLabelConfirmarSenha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelConfirmarSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConfirmarSenha.setText("Confirmar Senha");
        jPanel1.add(jLabelConfirmarSenha);
        jLabelConfirmarSenha.setBounds(150, 210, 130, 17);
        jPanel1.add(jPasswordFieldConfirmarSenha);
        jPasswordFieldConfirmarSenha.setBounds(150, 230, 260, 30);

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalvar.setText("Avançar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar);
        jButtonSalvar.setBounds(320, 320, 90, 30);

        jLabelCPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF");
        jPanel1.add(jLabelCPF);
        jLabelCPF.setBounds(150, 30, 28, 17);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCPFActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(150, 50, 260, 30);

        TelaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/3.jpg"))); // NOI18N
        jPanel1.add(TelaFundo);
        TelaFundo.setBounds(-10, 0, 540, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Biblioteca biblioteca = Biblioteca.getInstancia();
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        String login;
        String senha, confirm;
        String cpf;
        int ok = 0;
        
        try{
            cpf = getTextFieldData(jFormattedTextFieldCPF);
            login = getTextFieldData(jTextFieldUsuario);
            senha = getTextFieldData(jPasswordFieldSenha);
            confirm = getTextFieldData(jPasswordFieldConfirmarSenha);
  
            if(!senha.equals(confirm)){
                mensagemWarning("SENHAS NÃO CORRESPONDEM");
                limparCampos();
            }
            else{
                boolean aux = biblioteca.validarCadastroCliente(cpf, login);
                if(aux){
                    mensagemWarning("CLIENTE JÁ CADASTRADO!");
                    dispose();
                    ok++;
                } 
                else {
                    Cliente cliente = new Cliente(cpf, login, senha);
                    biblioteca.clientes.add(cliente);
                    dispose();
                    ok++;
                }      
        
            }
        }catch (FaltamDadosException ex){
            //Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            ex.View();
        }
        
        if(ok!=0){
            TelaFormularioCadastroCliente  telaCadastroCliente2 = new TelaFormularioCadastroCliente();
        
            telaCadastroCliente2.setVisible(true);
            dispose();
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jFormattedTextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPFActionPerformed
    
    public String getTextFieldData(JTextField jtext) throws FaltamDadosException {
		String s = jtext.getText();
		if (s.equals(""))
			throw new FaltamDadosException("Preencha todos os campos!");
		return s;
    }
    
    public void mensagemWarning(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
    }
    
    public void mensagemSucesso(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem, "SUCCESS", JOptionPane.PLAIN_MESSAGE);
    }
    
    public void limparCampos(){
        jPasswordFieldSenha.setText("");
	jPasswordFieldConfirmarSenha.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TelaFundo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelConfirmarSenha;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldConfirmarSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
